CREATE TABLE Deliveries
(
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWSEQUENTIALID(),
    OrderId UNIQUEIDENTIFIER NOT NULL,
    DeliveryAgentId UNIQUEIDENTIFIER NULL,
    DeliveryAddress NVARCHAR(MAX) NOT NULL,
    Status NVARCHAR(50) NOT NULL DEFAULT ('Pending'),
    AssignedAt DATETIMEOFFSET NULL,
    PickedUpAt DATETIMEOFFSET NULL,
    DeliveredAt DATETIMEOFFSET NULL,
    EstimatedDeliveryTime DATETIMEOFFSET NULL,

    FailureReason NVARCHAR(500) NULL,
    CancellationReason NVARCHAR(500) NULL,

    CreatedAt DATETIMEOFFSET NOT NULL DEFAULT SYSDATETIMEOFFSET(),
    UpdatedAt DATETIMEOFFSET NOT NULL DEFAULT SYSDATETIMEOFFSET()
);