CREATE TABLE DeliveryAgents
(
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWSEQUENTIALID(),
    Name NVARCHAR(100) NOT NULL,
    Email NVARCHAR(320) NULL,
    PhoneNumber NVARCHAR(32) NULL,
    Status NVARCHAR(50) NOT NULL DEFAULT ('Available'),
    Capacity INT NOT NULL DEFAULT 1,    
    IsOnline BIT NOT NULL DEFAULT 1,        
    Metadata NVARCHAR(MAX) NULL,            
    CreatedAt DATETIMEOFFSET NOT NULL DEFAULT SYSDATETIMEOFFSET(),
    UpdatedAt DATETIMEOFFSET NOT NULL DEFAULT SYSDATETIMEOFFSET()
);